FORMAT: 1A
HOST: http://www.google.com

# Payments
JSON contracts between back and front end for payments functionality

# Group Payments list

List of payments

Form parameters:
<ul>
    <li>transactionType</li>
    <li>transactionId</li>
    <li>pendingSort</li>
    <li>recentSort</li>
</ul>

_eventId:
<ul>
    <li>To payment detail: viewPayment</li>
</ul>

## List of payments [/pages/payments/list.json]
### Valid [GET]
+ Response 200 (application/json)

        {
            "header": {
                "showMenu": true,
                "hideBackButton": true
            },
            "crm": {
               "imageUrls": {
                    "def": "http://dev.medianet.es/compass-mobile/css/img/imageName.png",
                    "at2x": "http://dev.medianet.es/compass-mobile/css/img/imageName.@2x.png",
                    "hdpi": "http://dev.medianet.es/compass-mobile/css/img/imageName.hdpi.png",
                    "xhdpi": "http://dev.medianet.es/compass-mobile/css/img/imageName.xhdpi.png",
                    "xxhdpi": "http://dev.medianet.es/compass-mobile/css/img/imageName.xxhdpi.png"
                },
               "closeable": true,
               "location": "PAYMENTS"
            },
            "iwantto": {
                "size": 3
            },
            "pageContent": {
                "empty": false,
                "sortInfo": {
                    "criteria": 0,
                    "ascendant": false
                },
                "payments": [
                    {
                        "transactionId": "1234",
                        "status": "PENDING",
                        "date": 12351141411,
                        "description": "SPCA of Texas",
                        "amount": 100
                    },
                    {
                        "transactionId": "9876",
                        "status": "PENDING",
                        "date": 12355141411,
                        "description": "Compass Bank. Eric's Credit Card",
                        "amount": 1118.34
                    },
                    {
                        "transactionId": "7347626535732",
                        "status": "PROCESSED",
                        "date": 12451145411,
                        "description": "Centerpoint Energy. Forest Path Gas",
                        "amount": 32
                    },
                    {
                        "transactionId": "868649679354",
                        "status": "INPROCESS",
                        "date": 12351111411,
                        "description": "Chase Card Service. BizCard",
                        "amount": 3487.79
                    },
                    {
                        "transactionId": "459747835623",
                        "status": "CANCELLED",
                        "date": 12351111411,
                        "description": "City of Conroe. Manor House Water and Trash",
                        "amount": 256.76
                    },
                    {
                        "transactionId": "34864586422",
                        "status": "FAILED",
                        "date": 12351111411,
                        "description": "SHELL OIL",
                        "amount": 245.34
                    }
                ]
            }
        }

## Empty Payments [/pages/payments/list.json?mockId=empty]
### Valid [GET]
+ Response 200 (application/json)

        {
            "header": {
                "showMenu": true,
                "hideBackButton": true
            },
            "iwantto": {
                "size": 3
            },
            "pageContent": {
                "empty": true
            }
        }

# Group Payments Detail

Payment detail

Form parameters:
<ul>
    <li>transactionId</li>
</ul>

_eventId:
<ul>
    <li>To payment extended detail: viewExtendedPayment</li>
    <li>To payment list: back</li>
</ul>

## List of payments [/pages/payments/detail.json]
### Valid [GET]
+ Response 200 (application/json)

        {
            "header": {
                "showMenu": true,
                "title": "Payment detail"
            },
            "pageContent": {
                "empty": false,
                "activePaymentIndex": "3",
                "payments": [
                    {
                        "transactionId": "34864586422",
                        "status": "PENDING",
                        "date": 12351141411,
                        "effectiveDate": 12351141411,
                        "description": "SPCA of Texas",
                        "totalAmount": 100,
                        "amount": 100,
                        "feeAmount": 0,
                        "detailAvailable": true,
                        "paymentMethod": "Electronic",
                        "confirmationNumber": "CWETQ-QERRW",
                        "payeeAccountNumber": "625235622",
                        "fromAccount":{
                            "description":"checking",
                            "accountLast4":"2705"
                        }
                    },
                    {
                        "transactionId": "45676644784",
                        "status": "PENDING",
                        "date": 12355141411,
                        "effectiveDate": 12355141411,
                        "description": "Compass Bank. Eric's Credit Card",
                        "totalAmount": 1118.34,
                        "amount": 1115,
                        "feeAmount": 3.34,
                        "detailAvailable": true,
                        "paymentMethod": "Check",
                        "confirmationNumber": "CWTT2-QWWERR",
                        "payeeAccountNumber": "84687246",
                        "fromAccount":{
                            "description":"comcast",
                            "accountLast4":"0489"
                        }
                    },
                    {
                        "transactionId": "9887645574",
                        "status": "PROCESSED",
                        "date": 12451145411,
                        "effectiveDate": 12451145411,
                        "description": "Centerpoint Energy. Forest Path Gas",
                        "totalAmount": 32,
                        "amount": 31,
                        "feeAmount": 1,
                        "detailAvailable": false,
                        "paymentMethod": "Check",
                        "confirmationNumber": "TY2Y2-ET2G",
                        "payeeAccountNumber": "78548718",
                        "fromAccount":{
                            "description":"comcast",
                            "accountLast4":"0489"
                        }
                    },
                    {
                        "transactionId": "9567449744",
                        "status": "INPROCESS",
                        "date": 12351111411,
                        "effectiveDate": 12351111411,
                        "description": "Chase Card Service. BizCard",
                        "totalAmount": 3487.79,
                        "amount": 3487.79,
                        "feeAmount": 1,
                        "detailAvailable": false,
                        "paymentMethod": "Electronic",
                        "confirmationNumber": "AHCY2-AD22",
                        "payeeAccountNumber": "5647984154",
                        "fromAccount":{
                            "description":"comcast",
                            "accountLast4":"0489"
                        }
                    },
                    {
                        "transactionId": "8568354874379",
                        "status": "CANCELLED",
                        "date": 12351111411,
                        "effectiveDate": 12351111411,
                        "description": "City of Conroe. Manor House Water and Trash",
                        "totalAmount": 256.76,
                        "amount": 256.76,
                        "feeAmount": 0,
                        "detailAvailable": true,
                        "paymentMethod": "Electronic",
                        "confirmationNumber": "C2T2TY-ADGAS",
                        "payeeAccountNumber": "78518478",
                        "fromAccount":{
                            "description":"comcast",
                            "accountLast4":"0489"
                        }
                    },
                    {
                        "transactionId": "44836765753567",
                        "status": "FAILED",
                        "date": 12351111411,
                        "effectiveDate": 12351111411,
                        "description": "SHELL OIL",
                        "totalAmount": 245.34,
                        "amount": 240,
                        "feeAmount": 5.34,
                        "detailAvailable": false,
                        "paymentMethod": "Electronic",
                        "confirmationNumber": "CGAY-1H3H33",
                        "payeeAccountNumber": "33695225",
                        "fromAccount":{
                            "description":"comcast",
                            "accountLast4":"0489"
                        }
                    }
                ]
            },
            "flowExecutionUrl": "/api/payments/extendedDetail.json?execution=e1s1"
        }

## Payment confirmation [/pages/payments/detail.json?mockId=makePayment]
### Valid [GET]
+ Response 200 (application/json)

        {
            "header": {
                "showMenu": true,
                "modal": true,
                "title": "New Bill Payment"
            },
            "pageContent": {
                "empty": false,
                "activePaymentIndex": "3",
                "payments": [
                    {
                        "transactionId": "34864586422",
                        "status": "PENDING",
                        "date": 12351141411,
                        "effectiveDate": 12351141411,
                        "description": "SPCA of Texas",
                        "totalAmount": 100,
                        "amount": 100,
                        "feeAmount": 0,
                        "detailAvailable": true,
                        "paymentMethod": "Electronic",
                        "confirmationNumber": "CWETQ-QERRW",
                        "payeeAccountNumber": "625235622",
                        "fromAccount":{
                            "description":"checking",
                            "accountLast4":"2705"
                        }
                    }
                ]
            },
            "flowExecutionUrl": "/api/payments/extendedDetail.json?execution=e1s1"
        }

## Empty Payments [/pages/payments/detail.json?mockId=empty]
### Valid [GET]
+ Response 200 (application/json)

        {
            "header": {
                "showMenu": true
            },
            "pageContent": {
                "empty": true
            }
        }

# Group Payments Extended Detail

Payment extended detail

Form parameters: -
_eventId: -

## Card payment [/api/payments/extendedDetail.json]
### Card payment [GET]

+ Request (application/json)

        {
            "transactionId": "35615234143"
        }

+ Response 200 (application/json)

        {
            "alerts": null,
            "pageContent": {
                "cardNumber": "622345366311622",
                "checkNumber": null,
                "isAutomaticPayment": true,
                "payeeAccountNumber": "14621356611",
                "accountNumber": "6167211424662",
                "routingNumber": "113010547",
                "accountType": "DDA",
                "deliveryDate": 12351111411,
                "paymentMethod": "Electronic",
                "category": "Fuel"
            },
            "flowExecutionUrl": "/api/payments/extendedDetail.json?execution=e2s2"
        }

## Check payment [/api/payments/extendedDetail.json?mockId=check]
### Check payment [GET]

+ Request (application/json)

        {
            "transactionId": "35615234143"
        }

+ Response 200 (application/json)

        {
            "alerts": null,
            "pageContent": {
                "cardNumber": null,
                "checkNumber": "5225",
                "isAutomaticPayment": true,
                "payeeAccountNumber": "14621356611",
                "accountNumber": "6167211424662",
                "routingNumber": "113010547",
                "accountType": "DDA",
                "deliveryDate": 12351111411,
                "paymentMethod": "Electronic",
                "category": "Fuel"
            }
        }


## Alert [/api/payments/extendedDetail.json?mockId=alert]
### Alert [GET]

+ Request (application/json)

        {
            "transactionId": "35615234143"
        }

+ Response 200 (application/json)

        {
            "alerts": [
                {
                    "type": "ERROR",
                    "alert": [
                        {
                            "text": "Error message 1",
                            "field": ""
                        }
                    ]
                }
            ],
            "pageContent": null
        }

## Error [/api/payments/extendedDetail.json?mockId=error]
### Error [GET]

+ Request (application/json)

        {
            "transactionId": "35615234143"
        }

+ Response 500 (application/json)

        {
            "alerts": null,
            "pageContent": {
                "paymentMemo": "Memo",
                "cardNumber": null,
                "checkNumber": "5225",
                "creditDate": 156134112411,
                "debitDate": 123511414114,
                "deliveryDate": 12624623461,
                "isAutomaticPayment": true,
                "isPaymentFee": false,
                "paymentDelivery": null,
                "paymentNote": "Note",
                "payeeName": "Chevron",
                "payeeAccountNumber": "14621356611",
                "accountNumber": "6167211424662"
            }
        }

# Group Manage Pay Accounts

Manage Pay Accounts

Form parameters:
<ul>
    <li>selectedAccounts</li>
    <li>defaultAccount</li>
</ul>

_eventId:
<ul>
    <li>To submit: updateAccounts</li>
    <li>To close: close</li>
</ul>

## Manage Pay Accounts [/pages/payments/manageAccounts.json]
### Valid [GET]
+ Response 200 (application/json)

        {
            "header": {
                "showMenu": true
            },
            "pageContent": {
                "empty": false,
                "accounts":[
                    {
                        "key":"123456789",
                        "description":"BBVA - Personal Checking",
                        "accountNickName":"Johnny",
                        "accountLast4":"5566",
                        "checked": true,
                        "availableBal" : 0.0,
                        "accountDefault": false
                    },
                    {
                        "key":"234567891",
                        "description":"BBVA - Personal Checking",
                        "accountNickName":"Cuenta BBVA",
                        "accountLast4": "1561",
                        "checked": false,
                        "availableBal" : 0.0,
                        "accountDefault": false
                    },
                    {
                        "key":"1222",
                        "description":"BBVA - Personal Checking",
                        "accountNickName":"Cuenta BBVA",
                        "accountLast4": "1234",
                        "checked": true,
                        "availableBal" : 0.0,
                        "accountDefault": true
                    }
                ]   
                
            }
        }

# Group Make Payment

Make Payment

Form parameters:
<ul>
    <li>accountKey</li>
    <li>payeeId</li>
    <li>amount</li>
    <li>date</li>
</ul>

_eventId:
<ul>
    <li>To make Payment: makePayment</li>
    <li>To close: close</li>
</ul>

## Make Payment [/pages/payments/makePayment.json]
### Valid [GET]
+ Response 200 (application/json)

        {
            "header": {
                "showMenu": true
            },
            "pageContent": {
                "empty": false,
                "accounts":[
                    {
                        "key":"123456789",
                        "description":"BBVA - Personal Checking",
                        "accountNickName":"Johnny",
                        "accountLast4":"5566",
                        "availableBal": 11000,
                        "postedBal": 11000
                    },
                    {
                        "key":"234567891",
                        "description":"BBVA - Personal Checking",
                        "accountNickName":"Cuenta BBVA",
                        "accountLast4": "1561",
                        "availableBal": 1500,
                        "postedBal": 1500
                    },
                    {
                        "key":"1222",
                        "description":"BBVA - Personal Checking",
                        "accountNickName":"Cuenta BBVA",
                        "accountLast4": "1234",
                        "availableBal": 6000,
                        "postedBal": 6000
                    }
                ],
                "to": [
                    {
                        "accountLast4": "6133",
                        "payeeId": "241",
                        "payeeName": "James Bond",
                        "payeeNickName": "bond007",
                        "minDate": "2015-02-04",
                        "feePayment": true,
                        "feeLimitDate": "2015-02-10",
                        "feeLimitAmount": 3.00
                    },
                    {
                        "accountLast4": "5566",
                        "payeeId": "166259",
                        "payeeName": "Steve",
                        "payeeNickName": "Vaugh",
                        "minDate": "2014-09-26",
                        "ebillAvailable": true,
                        "ebill": {
                            "date": "2014-12-12",
                            "amount": 50
                        }
                    },
                    {
                        "accountLast4": "9282",
                        "payeeId": "156123",
                        "payeeName": "Steve",
                        "payeeNickName": "McQueen",
                        "minDate": "2014-09-30" 
                    },
                    {
                        "accountLast4": "6132",
                        "payeeId": "223422",
                        "payeeName": "Steve",
                        "payeeNickName": "Rogers",
                        "minDate": "2014-09-16" 
                    }
                ] 
            }
        }

## Make Payment one account [/pages/payments/makePayment.json?mockId=oneaccount]
### Valid [GET]
+ Response 200 (application/json)

        {
            "header": {
                "showMenu": true
            },
            "pageContent": {
                "empty": false,
                "accounts":[
                    {
                        "key":"123456789",
                        "description":"BBVA - Personal Checking",
                        "accountNickName":"Johnny",
                        "accountLast4":"5566",
                        "availableBal": 11000,
                        "postedBal": 11000
                    }
                ],
                "to": [
                    {
                        "accountLast4": "5566",
                        "payeeId": "166259",
                        "payeeName": "Steve",
                        "payeeNickName": "Vaugh",
                        "minDate": "2014-09-26",
                        "ebillEnabled": true,
                        "ebill": {
                            "date": "2014-12-16",
                            "amount": 150
                        } 
                    }
                ] 
            }
        }

## Edit make payment [/pages/payments/makePayment.json?mockId=editable]
### Valid [GET]
+ Response 200 (application/json)

        {
            "pageContent": {
                "accounts":[
                    {
                        "key":"123456789",
                        "description":"BBVA - Personal Checking",
                        "accountNickName":"Johnny",
                        "accountLast4":"5566",
                        "availableBal": 11000,
                        "postedBal": 11000
                    },
                    {
                        "key":"234567891",
                        "description":"BBVA - Personal Checking",
                        "accountNickName":"Cuenta BBVA",
                        "accountLast4": "1561",
                        "availableBal": 1500,
                        "postedBal": 1500
                    },
                    {
                        "key":"1222",
                        "description":"BBVA - Personal Checking",
                        "accountNickName":"Cuenta BBVA",
                        "accountLast4": "1234",
                        "availableBal": 6000,
                        "postedBal": 6000
                    }
                ],
                "to": [
                    {
                        "accountLast4": "6133",
                        "payeeId": "241",
                        "payeeName": "James Bond",
                        "payeeNickName": "bond007",
                        "minDate": "2014-09-19"
                    },
                    {
                        "accountLast4": "5566",
                        "payeeId": "166259",
                        "payeeName": "Steve",
                        "payeeNickName": "Vaugh",
                        "minDate": "2014-09-26"
                    },
                    {
                        "accountLast4": "9282",
                        "payeeId": "156123",
                        "payeeName": "Steve",
                        "payeeNickName": "McQueen",
                        "minDate": "2014-09-30",
                        "feePayment": true,
                        "feeLimitDate": "2015-02-10",
                        "feeLimitAmount": 3.00
                    },
                    {
                        "accountLast4": "6132",
                        "payeeId": "223422",
                        "payeeName": "Steve",
                        "payeeNickName": "Rogers",
                        "minDate": "2014-09-16"
                    }
                ],
                "userSelections": {
                    "fromAccount": "234567891",
                    "payeeId": "156123",
                    "amount": 300.00,
                    "date": 1422435999714
                }
            }
            
        }


# Group Make Payment Confirmation

Make Payment Confirmation

_eventId:
<ul>
    <li>To confirm payment: confirm</li>
    <li>To edit payment: edit</li>
    <li>To close: close</li>
</ul>

## Make Payment Confirmation [/pages/payments/makePaymentConfirmation.json]
### Valid [GET]
+ Response 200 (application/json)

        {
            "header": {
                "showMenu": true
            },
            "pageContent": {
                "date": 1410904800000,
                "from": {
                    "description": "Checking",
                    "accountLast4": "6423"
                }, 
                 "to": {
                    "description": "SPCA of Texas",
                    "accountLast4": null,
                    "payeeType": "company"
                },
                "totalAmount": 100,
                "amount": 100,
                "feeAmount": 0,
                "paymentMethod": "Electronic"
            }
        }
        
# Group Make Payment Detail

Make Payment Detail


## Make Payment Detail [/pages/payments/makePaymentDetail.json]
### Valid [GET]
+ Response 200 (application/json)

        {
            "header": {
                "showMenu": true
            },
            "pageContent": {
                "date": 1410904800000,
                "from": {
                    "description": "Checking",
                    "accountLast4": "6423"
                }, 
                 "to": {
                    "description": "SPCA of Texas",
                    "accountLast4": null,
                    "payeeType": "company"
                },
                "totalAmount": 100,
                "amount": 100,
                "feeAmount": 0,
                "paymentMethod": "Electronic"
            }
        }
        
# Group Manage Payees

Manage Pay Accounts

Form parameters:
<ul>
    <li>selectedAccounts</li>
    <li>defaultAccount</li>
</ul>

_eventId:
<ul>
    <li>To submit: updateAccounts</li>
    <li>To close: close</li>
</ul>

## List of Payees [/pages/payments/managePayees.json]
### Valid [GET]
+ Response 200 (application/json)

        {
            "header": {
                "showMenu": true
            },
            "iwantto": {
                "size": 2
            },
            "pageContent": [
                {
                    "payeeId": "1",
                    "payeeNickName": "Comcast",
                    "accountNumber": "8767998767-1",
                    "payeeType": "COMPANY"
                },
                {
                    "payeeId": "2",
                    "payeeNickName": "John Doe",
                    "phoneNumber": "555-555-5555",
                    "payeeType": "CUSTOMER"
                },
                {
                    "payeeId": "3",
                    "payeeNickName": "John Smith",
                    "phoneNumber": "555-555-5555",
                    "payeeType": "CUSTOMER"
                },
                {
                    "payeeId": "4",
                    "payeeNickName": "Reliant Energy",
                    "accountNumber": "6799877-1",
                    "payeeType": "COMPANY"
                }
            ]
        }

## Empty list of Payees [/pages/payments/managePayees.json?mockId=empty]
### Valid [GET]
+ Response 200 (application/json)

        {
            "header": {
                "showMenu": true
            },
            "iwantto": {
                "size": 2
            },
            "pageContent": {
                "empty": true
            }
        }

## Details of company payee [/pages/payments/payeeDetail.json]
### Valid [GET]
+ Response 200 (application/json)

        {
            "header": {
                "showMenu": true
            },
            "pageContent": {
                "id": "1",
                "nickName": "Comcast",
                "accountNumber": "8767998767-1",
                "payeeType": "COMPANY",
                "address": {
                    "street": "901 Jones Rd.",
                    "address2": "Austin, TX 63652"
                }
            }
        }

## Details of customer payee [/pages/payments/payeeDetail.json?mockId=customer]
### Valid [GET]
+ Response 200 (application/json)

        {
            "header": {
                "showMenu": true
            },
            "pageContent": {
                "id": "1",
                "nickName": "John Deacon",
                "phoneNumber": "5403646485",
                "payeeType": "CUSTOMER",
                "address": {
                    "street": "901 Jones Rd."
                }
            }
        }

# Group Add Payee

Shows the enrollment form

Form parameters:
<ul>
   <li>phoneNumber</li>
   <li>nickname</li>
   <li>street</li>
   <li>city</li>
   <li>zipCode</li>
   <li>fourZipCode</li>
   <li>state</li>
   <li>accountNumber</li>
   <li>accountNumberConfirm</li>
</ul>

    
_eventId: addPayee

## Correct answer [/pages/payments/addPayee.json]
### Activate [GET]
+ Response 200 (application/json)

        {
            "alerts": null, 
            "pageContent": null,
            "flowExecutionUrl": "/api/payments/searchPayees.json?mockId=2&_eventId=addPayee"
        }


# Group Search Payees

Search for payees, either companies or people

Form parameters: -

_eventId: searchPayee

## Successful phone number search [/api/payments/searchPayees.json]
### Valid [GET]
+ Response 200 (application/json)

        {
            "status": "OK",
            "pageContent": [
                {
                    "payeeName": "COMCAST CABLE",
                    "addressOnFile": true,
                    "merchantZipRequired": false
                }, {
                    "payeeName": "COMCAST OPINION",
                    "addressOnFile": false,
                    "address":{
                        "street":"311 PETERSON CIR",
                        "city":"GARDENDALE",
                        "state":"FL",
                        "zipCode":"35071",
                        "fourZipCode":"2740"
                    },
                    "merchantZipRequired": true
                }, {
                    "payeeName": "COMCAST PARABELLUM",
                    "addressOnFile": false,
                    "merchantZipRequired": true
                }

            ],
            "flowExecutionUrl": "/api/payments/addPayee.json?_eventId=addPayee"
        }

## Unsuccessful phone number search [/api/payments/searchPayees.json?mockId=2]
### Valid [GET]
+ Response 200 (application/json)

        {
            "status": "ERROR",
            "alerts": [
                {
                    "type": "INFO",
                    "alert": [
                        {
                            "text": "Phone number entered is unlisted.",
                            "field": "phoneNumber"
                        }
                    ]
                }
            ],
            "flowExecutionUrl": "/api/payments/searchPayees.json?_eventId=searchPayees"
        }

## Successful add payee [/api/payments/addPayee.json]
### Valid [GET]
+ Response 200 (application/json)

        {
            "status": "OK",
            "pageContent": null,
            "flowExecutionUrl": "/payments/managePayees.html?_eventId=complete"
        }

# Group Add Company

Shows the enrollment form

Form parameters:
<ul>
   <li>payeeName</li>
   <li>nickname</li>
   <li>street</li>
   <li>accountNumber</li>
   <li>accountNumberConfirm</li>
</ul>

    
_eventId:
<ul>
    <li>To add existant company or person: addPayee</li>
</ul>

## Correct answer [/pages/payments/addCompany.json]
### Activate [GET]
+ Response 200 (application/json)

        {
            "alerts": null, 
            "pageContent": null,
            "flowExecutionUrl": "/api/payments/searchCompany.json?_eventId=addPayee"
        }

## List of companies [/api/payments/searchCompany.json]
### Valid [GET]
+ Response 200 (application/json)

        {
            "status": "OK",
            "pageContent": [
                {
                    "payeeName": "COMCAST CABLE",
                    "addressOnFile": true,
                    "merchantZipRequired": false
                }, {
                    "payeeName": "COMCAST OPINION",
                    "addressOnFile": false,
                    "address":{
                        "street":"311 PETERSON CIR",
                        "city":"GARDENDALE",
                        "state":"FL",
                        "zipCode":"35071",
                        "fourZipCode":"2740"
                    },
                    "phoneNumber": 7854695623,
                    "merchantZipRequired": true
                }, {
                    "payeeName": "COMCAST PARABELLUM",
                    "addressOnFile": false,
                    "merchantZipRequired": true
                }

            ],
            "flowExecutionUrl": "/api/payments/addPayee.json?_eventId=addPayee"
        }

## Empty list of companies [/api/payments/searchCompany.json?mockId=2]
### Valid [GET]
+ Response 200 (application/json)

        {
            "status": "OK",
            "pageContent": [
            ],
            "flowExecutionUrl": "/api/payments/addPayee.json?_eventId=addPayee"
        }


